services:
  db-postgresql:
    restart: always
    image: postgres:15.1
    environment:
      POSTGRES_USER: jorge
      POSTGRES_PASSWORD: 13246
      POSTGRES_DB: auth
    volumes:
      - ./postgres-auth:/var/lib/postgresql
    ports:
      - 5435:5432
